fixing github workflow file

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -25,8 +25,8 @@ jobs:
           # Fetch tags
           git fetch --tags
 
-          # Get the latest tag (if no tag exists, default to 0.0.0-alpha)
-          last_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0-alpha")
+          # Get the latest tag (if no tag exists, default to 1.0.0-alpha)
+          last_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "1.0.0-alpha")
           echo "Last tag: $last_tag"
 
           # Extract major, minor, patch
@@ -36,7 +36,7 @@ jobs:
             patch=${BASH_REMATCH[3]}
             label=${BASH_REMATCH[4]}
           else
-            echo "Invalid tag format. Defaulting to 0.0.0-alpha."
+            echo "Invalid tag format. Defaulting to 1.0.0-alpha."
             major=0
             minor=0
             patch=0
